import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Main from './Main';
import {Provider} from "react-redux";
import store from "../redux/store"
import SimpleSnackbar from "@/components/MIUI/snackbar";
import {NavbarComponent} from "@/components/NavBarComponent";
import React from "react";
import Footer from "@/components/footer";
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
    <body className='bg-white overflow-auto'>
    <Main>
      <div className=' w-full flex items-center  flex-col px-[10%] justify-center pt-[20vh]'>
        <NavbarComponent className='top-2'/>
        {children}
      </div>
      <Footer/>
    </Main>
    </body>
    </html>
  );
}
